// AUTOGENERATED FROM PICO_CONFIG_HEADER_FILES and then PICO_<PLATFORM>_CONFIG_HEADER_FILES
// DO NOT EDIT!

// based on PICO_CONFIG_HEADER_FILES:

#include "cmsis/rename_exceptions.h"

// Conditional config based on target
#if defined(RP2040) || defined(PICO_RP2040)
// based on PICO_RP2040_CONFIG_HEADER_FILES:
// RP2040 configuration
#else
// based on PICO_RP2350_ARM_S_CONFIG_HEADER_FILES:
// RP2350 configuration
#endif
